spring:
  application:
    name: api-auth

  datasource:
    url: jdbc:mysql://localhost:3306/brofdi_auth
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: BSX+vZ5dP4jhCyMJjtU/+sjd/WjbpfrhiLOrl0++DCU=
  expirationMs: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9098
