
# myapp.yml dans le dépôt Git
spring:
  application:
    name: myapp
  datasource:
    url: jdbc:mysql://localhost:3306/myapp
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8085
