spring:
  application:
    name: SendVm
  eureka:
    client:
      server-url:
        defaultZone: http://localhost::8761/eureka/
   servlet:
    multipart:
      max-file-size: 60000000MB
      max-request-size: 60000000MB      
server:
  port: 7080
